# Generated by Django 3.2.6 on 2021-08-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('Customer_age', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
