# Generated by Django 3.2.6 on 2021-08-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Customer_age',
            new_name='customer_age',
        ),
    ]
